/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.stockops.UI;

import com.stockops.Business.EcoSystem;
import com.stockops.DB4OUtil.DB4OUtil;
import com.stockops.Roles.BrokerageModeratorRole;
import com.stockops.Roles.CommodityBrokerRole;
import com.stockops.Roles.CommodityMarketModeratorRole;
import com.stockops.Roles.CompanyManagerRole;
import com.stockops.Roles.DayTraderRole;
import com.stockops.Roles.EquityBrokerRole;
import com.stockops.Roles.EquityMarketModeratorRole;
import com.stockops.Roles.EstablishmentsModeratorRole;
import com.stockops.Roles.InvestmentManagerRoler;
import com.stockops.Roles.RetailInvestorRole;
import com.stockops.Roles.Role;
import javax.swing.JPanel;

/**
 *
 * @author mridulregmi
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    
    private EcoSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    
    public MainJFrame() {
        initComponents();
        system = dB4OUtil.retrieveSystem();
        setContainer(homeJPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane2 = new javax.swing.JSplitPane();
        rolesPanal = new javax.swing.JPanel();
        btnDayTrader = new javax.swing.JButton();
        btnCommodityBroker = new javax.swing.JButton();
        btnRetailInvestor = new javax.swing.JButton();
        btnCommodityMarketModerator = new javax.swing.JButton();
        btnEquityBroker = new javax.swing.JButton();
        btnEquityMarketModerator = new javax.swing.JButton();
        btnBrokersCommissionAdmin = new javax.swing.JButton();
        btnLicensingCommissionAdmin = new javax.swing.JButton();
        btnCompanyManager = new javax.swing.JButton();
        btnInvestmentsManager = new javax.swing.JButton();
        container = new javax.swing.JPanel();
        signupSigninJPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jPasswordField3 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtTitle = new javax.swing.JLabel();
        signInJPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        txtTitle2 = new javax.swing.JLabel();
        jPasswordField4 = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        homeJPanel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane2.setDividerLocation(250);

        rolesPanal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnDayTrader.setText("DayTrader");
        btnDayTrader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDayTraderActionPerformed(evt);
            }
        });

        btnCommodityBroker.setText("Commodity Broker");
        btnCommodityBroker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommodityBrokerActionPerformed(evt);
            }
        });

        btnRetailInvestor.setText("Retail Investor");
        btnRetailInvestor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetailInvestorActionPerformed(evt);
            }
        });

        btnCommodityMarketModerator.setText("Commodity Market Moderator");
        btnCommodityMarketModerator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommodityMarketModeratorActionPerformed(evt);
            }
        });

        btnEquityBroker.setText("Equity Broker");
        btnEquityBroker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEquityBrokerActionPerformed(evt);
            }
        });

        btnEquityMarketModerator.setText("Equity Market Moderator");
        btnEquityMarketModerator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEquityMarketModeratorActionPerformed(evt);
            }
        });

        btnBrokersCommissionAdmin.setText("Brokers Commission Admin");
        btnBrokersCommissionAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrokersCommissionAdminActionPerformed(evt);
            }
        });

        btnLicensingCommissionAdmin.setText("Licensing Commision Admin");
        btnLicensingCommissionAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLicensingCommissionAdminActionPerformed(evt);
            }
        });

        btnCompanyManager.setText("Company Manager");
        btnCompanyManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompanyManagerActionPerformed(evt);
            }
        });

        btnInvestmentsManager.setText("Investments Manager");
        btnInvestmentsManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvestmentsManagerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rolesPanalLayout = new javax.swing.GroupLayout(rolesPanal);
        rolesPanal.setLayout(rolesPanalLayout);
        rolesPanalLayout.setHorizontalGroup(
            rolesPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rolesPanalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rolesPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCommodityBroker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDayTrader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRetailInvestor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCommodityMarketModerator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEquityBroker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBrokersCommissionAdmin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEquityMarketModerator, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLicensingCommissionAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCompanyManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInvestmentsManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        rolesPanalLayout.setVerticalGroup(
            rolesPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rolesPanalLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnRetailInvestor, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDayTrader, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEquityBroker, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCommodityBroker, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEquityMarketModerator, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCommodityMarketModerator, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBrokersCommissionAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLicensingCommissionAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCompanyManager, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInvestmentsManager, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane2.setLeftComponent(rolesPanal);

        container.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        container.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Sign Up:");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setText("Sing In:");

        jLabel3.setText("Username:");

        jLabel4.setText("Password:");

        jLabel5.setText("Name:");

        jLabel6.setText("Username:");

        jLabel7.setText("Password:");

        jLabel8.setText("Confirm Password:");

        jButton1.setText("Sign In");

        jButton2.setText("Sign Up");

        txtTitle.setFont(new java.awt.Font("Myanmar MN", 0, 36)); // NOI18N
        txtTitle.setText("PORTAL");

        javax.swing.GroupLayout signupSigninJPanelLayout = new javax.swing.GroupLayout(signupSigninJPanel);
        signupSigninJPanel.setLayout(signupSigninJPanelLayout);
        signupSigninJPanelLayout.setHorizontalGroup(
            signupSigninJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signupSigninJPanelLayout.createSequentialGroup()
                .addGroup(signupSigninJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signupSigninJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(signupSigninJPanelLayout.createSequentialGroup()
                            .addGroup(signupSigninJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(signupSigninJPanelLayout.createSequentialGroup()
                                    .addGap(81, 81, 81)
                                    .addGroup(signupSigninJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1)))
                                .addGroup(signupSigninJPanelLayout.createSequentialGroup()
                                    .addGap(96, 96, 96)
                                    .addGroup(signupSigninJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(signupSigninJPanelLayout.createSequentialGroup()
                                            .addGroup(signupSigninJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(signupSigninJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel3)
                                                    .addComponent(jLabel4))
                                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(signupSigninJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jPasswordField1)
                                                .addComponent(jTextField2)
                                                .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)))
                                        .addGroup(signupSigninJPanelLayout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(signupSigninJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(signupSigninJPanelLayout.createSequentialGroup()
                                                    .addGap(1, 1, 1)
                                                    .addComponent(jPasswordField2, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                                                .addComponent(jTextField4)))
                                        .addGroup(signupSigninJPanelLayout.createSequentialGroup()
                                            .addGap(3, 3, 3)
                                            .addComponent(jLabel6))))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signupSigninJPanelLayout.createSequentialGroup()
                                    .addGap(47, 47, 47)
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jPasswordField3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(40, 40, 40))
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(signupSigninJPanelLayout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(txtTitle)))
                .addContainerGap(339, Short.MAX_VALUE))
        );
        signupSigninJPanelLayout.setVerticalGroup(
            signupSigninJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signupSigninJPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(txtTitle)
                .addGap(55, 55, 55)
                .addComponent(jLabel2)
                .addGap(20, 20, 20)
                .addGroup(signupSigninJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(signupSigninJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(22, 22, 22)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addGroup(signupSigninJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(signupSigninJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(signupSigninJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(signupSigninJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jPasswordField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        container.add(signupSigninJPanel, "card2");

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel10.setText("Sing In:");

        jLabel11.setText("Username:");

        jLabel12.setText("Password:");

        txtTitle2.setFont(new java.awt.Font("Myanmar MN", 0, 36)); // NOI18N
        txtTitle2.setText("PORTAL");

        jButton3.setText("Sign In");

        javax.swing.GroupLayout signInJPanelLayout = new javax.swing.GroupLayout(signInJPanel);
        signInJPanel.setLayout(signInJPanelLayout);
        signInJPanelLayout.setHorizontalGroup(
            signInJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signInJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTitle2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(signInJPanelLayout.createSequentialGroup()
                .addGroup(signInJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addGroup(signInJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(signInJPanelLayout.createSequentialGroup()
                            .addGap(130, 130, 130)
                            .addComponent(jLabel10))
                        .addGroup(signInJPanelLayout.createSequentialGroup()
                            .addGap(146, 146, 146)
                            .addComponent(jLabel11))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(signInJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addComponent(jPasswordField4))
                .addGap(311, 311, 311))
            .addGroup(signInJPanelLayout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        signInJPanelLayout.setVerticalGroup(
            signInJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signInJPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(txtTitle2)
                .addGap(53, 53, 53)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(signInJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(signInJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jPasswordField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(342, Short.MAX_VALUE))
        );

        container.add(signInJPanel, "card3");

        jLabel14.setFont(new java.awt.Font("Myanmar MN", 0, 36)); // NOI18N
        jLabel14.setText("Welcome To StockOps");

        javax.swing.GroupLayout homeJPanelLayout = new javax.swing.GroupLayout(homeJPanel);
        homeJPanel.setLayout(homeJPanelLayout);
        homeJPanelLayout.setHorizontalGroup(
            homeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeJPanelLayout.createSequentialGroup()
                .addContainerGap(195, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addContainerGap(144, Short.MAX_VALUE))
        );
        homeJPanelLayout.setVerticalGroup(
            homeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeJPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel14)
                .addContainerGap(575, Short.MAX_VALUE))
        );

        container.add(homeJPanel, "card4");

        jSplitPane2.setRightComponent(container);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCommodityBrokerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommodityBrokerActionPerformed
        setRightPanalSignInUp(new CommodityBrokerRole(), "Commodity Broker");
    }//GEN-LAST:event_btnCommodityBrokerActionPerformed

    private void btnDayTraderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDayTraderActionPerformed
        setRightPanalSignInUp(new DayTraderRole(), "Day Trader");
    }//GEN-LAST:event_btnDayTraderActionPerformed

    private void btnCommodityMarketModeratorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommodityMarketModeratorActionPerformed
        setRightPanalSignIn(new CommodityMarketModeratorRole(), "Commodity Futures Trading Commission");
    }//GEN-LAST:event_btnCommodityMarketModeratorActionPerformed

    private void btnEquityBrokerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEquityBrokerActionPerformed
        setRightPanalSignInUp(new EquityBrokerRole(), "Equity Broker");
    }//GEN-LAST:event_btnEquityBrokerActionPerformed

    private void btnEquityMarketModeratorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEquityMarketModeratorActionPerformed
        setRightPanalSignIn(new CompanyManagerRole(), "Securities and Exchange Board");
    }//GEN-LAST:event_btnEquityMarketModeratorActionPerformed

    private void btnBrokersCommissionAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrokersCommissionAdminActionPerformed
        setRightPanalSignIn(new BrokerageModeratorRole(), "Brokers Commmission Admin");
    }//GEN-LAST:event_btnBrokersCommissionAdminActionPerformed

    private void btnLicensingCommissionAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLicensingCommissionAdminActionPerformed
        setRightPanalSignIn(new EstablishmentsModeratorRole(), "Licensing Commission Admin");
    }//GEN-LAST:event_btnLicensingCommissionAdminActionPerformed

    private void btnCompanyManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompanyManagerActionPerformed
        setRightPanalSignInUp(new CompanyManagerRole(), "Company Manager");
    }//GEN-LAST:event_btnCompanyManagerActionPerformed

    private void btnInvestmentsManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvestmentsManagerActionPerformed
        setRightPanalSignInUp(new InvestmentManagerRoler(), "Investment Manager");
    }//GEN-LAST:event_btnInvestmentsManagerActionPerformed

    private void btnRetailInvestorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetailInvestorActionPerformed
        setRightPanalSignInUp(new RetailInvestorRole(), "Retail Investor");
    }//GEN-LAST:event_btnRetailInvestorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrokersCommissionAdmin;
    private javax.swing.JButton btnCommodityBroker;
    private javax.swing.JButton btnCommodityMarketModerator;
    private javax.swing.JButton btnCompanyManager;
    private javax.swing.JButton btnDayTrader;
    private javax.swing.JButton btnEquityBroker;
    private javax.swing.JButton btnEquityMarketModerator;
    private javax.swing.JButton btnInvestmentsManager;
    private javax.swing.JButton btnLicensingCommissionAdmin;
    private javax.swing.JButton btnRetailInvestor;
    private javax.swing.JPanel container;
    private javax.swing.JPanel homeJPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JPasswordField jPasswordField4;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JPanel rolesPanal;
    private javax.swing.JPanel signInJPanel;
    private javax.swing.JPanel signupSigninJPanel;
    private javax.swing.JLabel txtTitle;
    private javax.swing.JLabel txtTitle2;
    // End of variables declaration//GEN-END:variables

    private void setContainer(JPanel newJPanel) {
        container.removeAll();
        container.add(newJPanel);
        container.revalidate();
        container.repaint();
    }

    private void setRightPanalSignInUp(Role role, String titleText) {
        txtTitle.setText(titleText);
        setContainer(signupSigninJPanel);
    }
    
    private void setRightPanalSignIn(Role role, String titleText) {
        txtTitle2.setText(titleText);
        setContainer(signInJPanel);
    }
}
