/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.stockops.UI;

import com.stockops.Brokerage.BrokerageModerator;
import com.stockops.Brokerage.CommodityBroker;
import com.stockops.Brokerage.EquityBroker;
import com.stockops.Business.EcoSystem;
import com.stockops.DB4OUtil.DB4OUtil;
import com.stockops.Establishments.Company;
import com.stockops.Establishments.CompanyManager;
import com.stockops.Establishments.EstablishmentsModerator;
import com.stockops.Establishments.InvestmentManager;
import com.stockops.Investor.DayTrader;
import com.stockops.Investor.RetailInvestor;
import com.stockops.Market.CommodityMarketModerator;
import com.stockops.Roles.BrokerageModeratorRole;
import com.stockops.Roles.CommodityBrokerRole;
import com.stockops.Roles.CommodityMarketModeratorRole;
import com.stockops.Roles.CompanyManagerRole;
import com.stockops.Roles.MarketAnalyst;
import com.stockops.Roles.EquityBrokerRole;
import com.stockops.Roles.EquityMarketModeratorRole;
import com.stockops.Roles.EstablishmentsModeratorRole;
import com.stockops.Roles.InvestmentManagerRole;
import com.stockops.Roles.RetailInvestorRole;
import com.stockops.Roles.Role;
import com.stockops.Users.AppUser;
import com.stockops.Users.UserAccount;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author mridulregmi
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    
    private EcoSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    AppUser selectedUser;
    Role role;
    
    public MainJFrame() {
        initComponents();
        system = dB4OUtil.retrieveSystem();
        setContainer(homeJPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane2 = new javax.swing.JSplitPane();
        rolesPanal = new javax.swing.JPanel();
        btnDayTrader = new javax.swing.JButton();
        btnCommodityBroker = new javax.swing.JButton();
        btnRetailInvestor = new javax.swing.JButton();
        btnCommodityMarketModerator = new javax.swing.JButton();
        btnEquityBroker = new javax.swing.JButton();
        btnEquityMarketModerator = new javax.swing.JButton();
        btnBrokersCommissionAdmin = new javax.swing.JButton();
        btnLicensingCommissionAdmin = new javax.swing.JButton();
        btnCompanyManager = new javax.swing.JButton();
        btnInvestmentsManager = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        container = new javax.swing.JPanel();
        signInJPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        txtTitle2 = new javax.swing.JLabel();
        jPasswordField4 = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        homeJPanel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        investmentManagerJPanel = new javax.swing.JPanel();
        txtTitle1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPasswordField5 = new javax.swing.JPasswordField();
        jButton4 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jPasswordField6 = new javax.swing.JPasswordField();
        jLabel20 = new javax.swing.JLabel();
        jPasswordField7 = new javax.swing.JPasswordField();
        jButton5 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        signupSigninJPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jPasswordField3 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtTitle = new javax.swing.JLabel();
        jlblnoaccount = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane2.setBackground(new java.awt.Color(0, 51, 51));
        jSplitPane2.setDividerLocation(250);

        rolesPanal.setBackground(new java.awt.Color(54, 33, 89));
        rolesPanal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnDayTrader.setBackground(new java.awt.Color(85, 65, 118));
        btnDayTrader.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDayTrader.setForeground(new java.awt.Color(255, 255, 255));
        btnDayTrader.setText("Market Analyst");
        btnDayTrader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDayTraderActionPerformed(evt);
            }
        });

        btnCommodityBroker.setBackground(new java.awt.Color(85, 65, 118));
        btnCommodityBroker.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCommodityBroker.setForeground(new java.awt.Color(255, 255, 255));
        btnCommodityBroker.setText("Commodity Broker");
        btnCommodityBroker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommodityBrokerActionPerformed(evt);
            }
        });

        btnRetailInvestor.setBackground(new java.awt.Color(85, 65, 118));
        btnRetailInvestor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRetailInvestor.setForeground(new java.awt.Color(255, 255, 255));
        btnRetailInvestor.setText("Retail Investor");
        btnRetailInvestor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetailInvestorActionPerformed(evt);
            }
        });

        btnCommodityMarketModerator.setBackground(new java.awt.Color(85, 65, 118));
        btnCommodityMarketModerator.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCommodityMarketModerator.setForeground(new java.awt.Color(255, 255, 255));
        btnCommodityMarketModerator.setText("Commodity Market Moderator");
        btnCommodityMarketModerator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommodityMarketModeratorActionPerformed(evt);
            }
        });

        btnEquityBroker.setBackground(new java.awt.Color(85, 65, 118));
        btnEquityBroker.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEquityBroker.setForeground(new java.awt.Color(255, 255, 255));
        btnEquityBroker.setText("Equity Broker");
        btnEquityBroker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEquityBrokerActionPerformed(evt);
            }
        });

        btnEquityMarketModerator.setBackground(new java.awt.Color(85, 65, 118));
        btnEquityMarketModerator.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEquityMarketModerator.setForeground(new java.awt.Color(255, 255, 255));
        btnEquityMarketModerator.setText("Equity Market Moderator");
        btnEquityMarketModerator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEquityMarketModeratorActionPerformed(evt);
            }
        });

        btnBrokersCommissionAdmin.setBackground(new java.awt.Color(85, 65, 118));
        btnBrokersCommissionAdmin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBrokersCommissionAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnBrokersCommissionAdmin.setText("Brokers Commission Admin");
        btnBrokersCommissionAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrokersCommissionAdminActionPerformed(evt);
            }
        });

        btnLicensingCommissionAdmin.setBackground(new java.awt.Color(85, 65, 118));
        btnLicensingCommissionAdmin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLicensingCommissionAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnLicensingCommissionAdmin.setText("Establishment Moderator");
        btnLicensingCommissionAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLicensingCommissionAdminActionPerformed(evt);
            }
        });

        btnCompanyManager.setBackground(new java.awt.Color(85, 65, 118));
        btnCompanyManager.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCompanyManager.setForeground(new java.awt.Color(255, 255, 255));
        btnCompanyManager.setText("Company Manager");
        btnCompanyManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompanyManagerActionPerformed(evt);
            }
        });

        btnInvestmentsManager.setBackground(new java.awt.Color(85, 65, 118));
        btnInvestmentsManager.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInvestmentsManager.setForeground(new java.awt.Color(255, 255, 255));
        btnInvestmentsManager.setText("Investments Manager");
        btnInvestmentsManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvestmentsManagerActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Select Your Role");

        javax.swing.GroupLayout rolesPanalLayout = new javax.swing.GroupLayout(rolesPanal);
        rolesPanal.setLayout(rolesPanalLayout);
        rolesPanalLayout.setHorizontalGroup(
            rolesPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rolesPanalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rolesPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCommodityBroker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDayTrader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRetailInvestor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCommodityMarketModerator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEquityBroker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBrokersCommissionAdmin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEquityMarketModerator, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLicensingCommissionAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCompanyManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInvestmentsManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(rolesPanalLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel23)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rolesPanalLayout.setVerticalGroup(
            rolesPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rolesPanalLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel23)
                .addGap(21, 21, 21)
                .addComponent(btnRetailInvestor, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDayTrader, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEquityBroker, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCommodityBroker, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEquityMarketModerator, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCommodityMarketModerator, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBrokersCommissionAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLicensingCommissionAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCompanyManager, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInvestmentsManager, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(279, Short.MAX_VALUE))
        );

        jSplitPane2.setLeftComponent(rolesPanal);

        container.setBackground(new java.awt.Color(255, 255, 255));
        container.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        container.setLayout(new java.awt.CardLayout());

        signInJPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Username:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Password:");

        txtTitle2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        txtTitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTitle2.setText("PORTAL");

        jButton3.setBackground(new java.awt.Color(85, 65, 118));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Sign In");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout signInJPanelLayout = new javax.swing.GroupLayout(signInJPanel);
        signInJPanel.setLayout(signInJPanelLayout);
        signInJPanelLayout.setHorizontalGroup(
            signInJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signInJPanelLayout.createSequentialGroup()
                .addGroup(signInJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signInJPanelLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addGroup(signInJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(signInJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                            .addComponent(jPasswordField4)))
                    .addGroup(signInJPanelLayout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(835, Short.MAX_VALUE))
            .addComponent(txtTitle2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        signInJPanelLayout.setVerticalGroup(
            signInJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signInJPanelLayout.createSequentialGroup()
                .addComponent(txtTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addGroup(signInJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(signInJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(37, 37, 37)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(584, Short.MAX_VALUE))
        );

        container.add(signInJPanel, "card3");

        homeJPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel14.setText("Welcome To StockOps");

        jLabel24.setIcon(new javax.swing.ImageIcon("/Users/mridulregmi/Desktop/AED-Final-Project/images/stock.png")); // NOI18N

        javax.swing.GroupLayout homeJPanelLayout = new javax.swing.GroupLayout(homeJPanel);
        homeJPanel.setLayout(homeJPanelLayout);
        homeJPanelLayout.setHorizontalGroup(
            homeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 1157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        homeJPanelLayout.setVerticalGroup(
            homeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeJPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 813, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        container.add(homeJPanel, "card4");

        txtTitle1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        txtTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTitle1.setText("PORTAL");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Username:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Password:");

        jButton4.setBackground(new java.awt.Color(85, 65, 118));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Sign In");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Name:");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Username:");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Password:");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Confirm Password:");

        jButton5.setBackground(new java.awt.Color(85, 65, 118));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Sign Up");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Experience:");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Salary:");

        javax.swing.GroupLayout investmentManagerJPanelLayout = new javax.swing.GroupLayout(investmentManagerJPanel);
        investmentManagerJPanel.setLayout(investmentManagerJPanelLayout);
        investmentManagerJPanelLayout.setHorizontalGroup(
            investmentManagerJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(investmentManagerJPanelLayout.createSequentialGroup()
                .addGroup(investmentManagerJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(investmentManagerJPanelLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(investmentManagerJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(investmentManagerJPanelLayout.createSequentialGroup()
                                .addGroup(investmentManagerJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel18)
                                    .addGroup(investmentManagerJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel15))
                                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(investmentManagerJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(investmentManagerJPanelLayout.createSequentialGroup()
                                        .addGap(91, 91, 91)
                                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, investmentManagerJPanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(investmentManagerJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(investmentManagerJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPasswordField5, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, investmentManagerJPanelLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(investmentManagerJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel19)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(investmentManagerJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(investmentManagerJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPasswordField6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPasswordField7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(799, Short.MAX_VALUE))
            .addComponent(txtTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        investmentManagerJPanelLayout.setVerticalGroup(
            investmentManagerJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(investmentManagerJPanelLayout.createSequentialGroup()
                .addComponent(txtTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addGroup(investmentManagerJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(investmentManagerJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(investmentManagerJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(investmentManagerJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(investmentManagerJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(18, 18, 18)
                .addGroup(investmentManagerJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(investmentManagerJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jPasswordField6, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(investmentManagerJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(38, 38, 38)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(173, 173, 173))
        );

        container.add(investmentManagerJPanel, "card5");

        signupSigninJPanel.setBackground(new java.awt.Color(255, 255, 255));
        signupSigninJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setText("Username:");
        signupSigninJPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 89, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setText("Password:");
        signupSigninJPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 89, 22));
        signupSigninJPanel.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 162, 190, 30));
        signupSigninJPanel.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 212, 190, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setText("Name:");
        signupSigninJPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, -1, -1));
        signupSigninJPanel.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 190, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel6.setText("Username:");
        signupSigninJPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, -1, -1));
        signupSigninJPanel.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 190, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel7.setText("Password:");
        signupSigninJPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, -1, -1));
        signupSigninJPanel.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, 190, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel8.setText("Confirm Password:");
        signupSigninJPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 520, -1, -1));
        signupSigninJPanel.add(jPasswordField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, 190, 30));

        jButton1.setBackground(new java.awt.Color(85, 65, 118));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Sign In");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        signupSigninJPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 100, 40));

        jButton2.setBackground(new java.awt.Color(85, 65, 118));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Sign Up");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        signupSigninJPanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 580, 110, 40));

        txtTitle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        txtTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTitle.setText("PORTAL");
        signupSigninJPanel.add(txtTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 50));

        jlblnoaccount.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jlblnoaccount.setText("Don't have account?");
        signupSigninJPanel.add(jlblnoaccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 580, 150, 46));

        container.add(signupSigninJPanel, "card2");

        jSplitPane2.setRightComponent(container);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCommodityBrokerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommodityBrokerActionPerformed
        this.selectedUser=new CommodityBroker();
        this.role = new CommodityBrokerRole();
        setRightPanalSignInUp(this.role, "Commodity Broker");
        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_btnCommodityBrokerActionPerformed

    private void btnDayTraderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDayTraderActionPerformed
        this.selectedUser=new DayTrader();
        this.role=new MarketAnalyst();
        setRightPanalSignIn(this.role, "Market Analyst");
//        setRightPanalSignInUp(this.role, "Market Analyst");
        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_btnDayTraderActionPerformed

    private void btnCommodityMarketModeratorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommodityMarketModeratorActionPerformed
        this.selectedUser=new CommodityMarketModerator();
        this.role=new CommodityMarketModeratorRole();
        setRightPanalSignIn(this.role, "Commodity Futures Trading Commission");
        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_btnCommodityMarketModeratorActionPerformed

    private void btnEquityBrokerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEquityBrokerActionPerformed
        this.selectedUser=new EquityBroker();
        this.role=new EquityBrokerRole();
        setRightPanalSignInUp(this.role, "Equity Broker");
        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_btnEquityBrokerActionPerformed

    private void btnEquityMarketModeratorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEquityMarketModeratorActionPerformed
        this.selectedUser=new CompanyManager();
        this.role=new EquityMarketModeratorRole();
        setRightPanalSignIn(this.role, "Securities and Exchange Board");
        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_btnEquityMarketModeratorActionPerformed

    private void btnBrokersCommissionAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrokersCommissionAdminActionPerformed
        this.selectedUser=new BrokerageModerator();
        this.role=new BrokerageModeratorRole();
        setRightPanalSignIn(this.role, "Brokers Commmission Admin");
        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_btnBrokersCommissionAdminActionPerformed

    private void btnLicensingCommissionAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLicensingCommissionAdminActionPerformed
        this.selectedUser=new EstablishmentsModerator();
        this.role=new EstablishmentsModeratorRole();
        setRightPanalSignIn(this.role, "Establishments Moderator");
        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_btnLicensingCommissionAdminActionPerformed

    private void btnCompanyManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompanyManagerActionPerformed
        this.selectedUser=new CompanyManager();
        this.role=new CompanyManagerRole();
        setRightPanalSignInUp(this.role, "Company Manager");
        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_btnCompanyManagerActionPerformed

    private void btnInvestmentsManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvestmentsManagerActionPerformed
        this.selectedUser=new InvestmentManager();
        this.role=new InvestmentManagerRole();
        setRightPanalSignInUp(this.role, "Investment Manager");
        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_btnInvestmentsManagerActionPerformed

    private void btnRetailInvestorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetailInvestorActionPerformed
        this.selectedUser=new RetailInvestor();
        this.role=new RetailInvestorRole();
        setRightPanalSignInUp(this.role, "Retail Investor");
        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_btnRetailInvestorActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        char[] password=jPasswordField4.getPassword();
        String passwordString = new String(password);
        UserAccount user=system.getUserDirectory().authenticateUser(jTextField5.getText(), passwordString);
        if(user!=null && (user.getRole().getClass()==this.role.getClass())){
            setContainer(user.getRole().createWorkArea(container, user, system));
        }
        else{
            JOptionPane.showMessageDialog(this, "Invalid Username or Password!");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        char[] password=jPasswordField5.getPassword();
        String passwordString = new String(password);
        UserAccount user=system.getUserDirectory().authenticateUser(jTextField4.getText(), passwordString);
        if(user!=null && user.getRole()==this.role){
            setContainer(user.getRole().createWorkArea(container, user, system));
        }
        else{
            JOptionPane.showMessageDialog(this, "Invalid Username or Password!");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        char[] password=jPasswordField6.getPassword();
        String passwordString = new String(password);
        char[] confirmPassword=jPasswordField6.getPassword();
        String confirmPasswordString = new String(confirmPassword);
        if(!passwordString.equals(confirmPasswordString)){
            JOptionPane.showMessageDialog(this, "Passwords Do Not Match");
        }
        else{
            selectedUser.setName(jTextField7.getText());
            selectedUser.setUserId(system.getUserCount());
            system.setUserCount(system.getUserCount()+1);
            ((InvestmentManager)selectedUser).setExperience(Float.parseFloat(jTextField9.getText()));
            ((InvestmentManager)selectedUser).setSalary(Double.parseDouble(jTextField1.getText()));
            UserAccount user=this.system.getUserDirectory().createUserAccount(jTextField4.getText(), passwordString, selectedUser, role);
            this.system.getEstablishment().getEstablishmentsModerator().getInvestmentManagerDirectory().add((InvestmentManager)selectedUser);
            JOptionPane.showMessageDialog(this, "User Signed In Successfully");
            setContainer(user.getRole().createWorkArea(container, user, system));
        }
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        char[] password=jPasswordField2.getPassword();
        String passwordString = new String(password);
        char[] confirmPassword=jPasswordField3.getPassword();
        String confirmPasswordString = new String(confirmPassword);
        String username=jTextField4.getText();
        if(validPassword(passwordString)){
            if(!passwordString.equals(confirmPasswordString)){
                JOptionPane.showMessageDialog(this, "Passwords Do Not Match");
            }
            else{
                selectedUser.setName(jTextField3.getText());
                selectedUser.setUserId(system.getUserCount());
                system.setUserCount(system.getUserCount()+1);
                if(this.system.getUserDirectory().checkIfUsernameIsUnique(username)){
                    UserAccount user=this.system.getUserDirectory().createUserAccount(username, passwordString, selectedUser, role);
                    if(role instanceof CommodityBrokerRole){
                        this.system.getBrokerage().getCommodityBrokersDirectory().add((CommodityBroker)selectedUser);
                    }
                    else if(role instanceof EquityBrokerRole){
                        this.system.getBrokerage().getEquityBrokersDirectory().add((EquityBroker)selectedUser);
                    }
                    else if(role instanceof RetailInvestorRole){
                        this.system.getInvestor().getRetailInvestorDirectory().add((RetailInvestor)selectedUser);
                    }
                    else if(role instanceof InvestmentManagerRole){
                        this.system.getEstablishment().getEstablishmentsModerator().getInvestmentManagerDirectory().add((InvestmentManager)selectedUser);
                    }
                    else if(role instanceof CompanyManagerRole){
                        this.system.getEstablishment().getEstablishmentsModerator().getCompanyManagerDirectory().add((CompanyManager)selectedUser);
                    }
                    else{
                        this.system.getInvestor().getDayTraderDirectory().add((DayTrader)selectedUser);
                    }
                    JOptionPane.showMessageDialog(this, "User Signed In Successfully");
                    setContainer(user.getRole().createWorkArea(container, user, system));
                    jTextField2.setText("");
                    jPasswordField1.setText("");
                    jPasswordField2.setText("");
                    jPasswordField3.setText("");
                    jTextField4.setText("");
                    jTextField3.setText("");
                    jTextField5.setText("");
                    jPasswordField5.setText("");
                }
                else{
                    JOptionPane.showMessageDialog(this, "User Name Already Taken");
                }
            }
        }else{
            JOptionPane.showMessageDialog(this, "Password too weak!");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        char[] password=jPasswordField1.getPassword();
        String passwordString = new String(password);
        UserAccount user=system.getUserDirectory().authenticateUser(jTextField2.getText(), passwordString);
        if(user!=null && (user.getRole().getClass()==this.role.getClass())){
            setContainer(user.getRole().createWorkArea(container, user, system));
        }
        else{
            JOptionPane.showMessageDialog(this, "Invalid Username or Password!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrokersCommissionAdmin;
    private javax.swing.JButton btnCommodityBroker;
    private javax.swing.JButton btnCommodityMarketModerator;
    private javax.swing.JButton btnCompanyManager;
    private javax.swing.JButton btnDayTrader;
    private javax.swing.JButton btnEquityBroker;
    private javax.swing.JButton btnEquityMarketModerator;
    private javax.swing.JButton btnInvestmentsManager;
    private javax.swing.JButton btnLicensingCommissionAdmin;
    private javax.swing.JButton btnRetailInvestor;
    private javax.swing.JPanel container;
    private javax.swing.JPanel homeJPanel;
    private javax.swing.JPanel investmentManagerJPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JPasswordField jPasswordField4;
    private javax.swing.JPasswordField jPasswordField5;
    private javax.swing.JPasswordField jPasswordField6;
    private javax.swing.JPasswordField jPasswordField7;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel jlblnoaccount;
    private javax.swing.JPanel rolesPanal;
    private javax.swing.JPanel signInJPanel;
    private javax.swing.JPanel signupSigninJPanel;
    private javax.swing.JLabel txtTitle;
    private javax.swing.JLabel txtTitle1;
    private javax.swing.JLabel txtTitle2;
    // End of variables declaration//GEN-END:variables

    private void setContainer(JPanel newJPanel) {
        container.removeAll();
        container.add(newJPanel);
        container.revalidate();
        container.repaint();
    }

    private void setRightPanalSignInUp(Role role, String titleText) {
        txtTitle.setText(titleText);
        setContainer(signupSigninJPanel);
    }
    
    private void setRightPanalSignIn(Role role, String titleText) {
        txtTitle2.setText(titleText);
        setContainer(signInJPanel);
    }

    private void setRightPanalInvestmentManager(Role role, String investment_Manager) {
        txtTitle1.setText(investment_Manager);
        setContainer(signupSigninJPanel);
    }
    
    
    private Boolean validPassword(String password1) {
        String regex = "^(?=.*\\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%]).{8,20}$";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(password1);
        return matcher.matches();
    }
}
