/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.stockops.UI.CompanyManger;

import com.stockops.Business.EcoSystem;
import com.stockops.Establishments.Company;
import com.stockops.Establishments.CompanyManager;
import com.stockops.Establishments.InvestmentManager;
import com.stockops.Establishments.JobRequest;
import com.stockops.Market.Equity;
import com.stockops.Market.ListingRequest;
import com.stockops.Users.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author knd18
 */
public class CompanyManagerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CompanyManagerHomePageJPanel
     */
    JPanel userProcessContainer;
    UserAccount account;
    EcoSystem business;
    CompanyManager manager;
    Company selectedCompany;
    public CompanyManagerJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem business ) {
        this.userProcessContainer=userProcessContainer;
        this.account=account;
        this.business=business;
        this.manager = (CompanyManager)account.getUser();
        initComponents();
        setComponent(homepage);
        populateRegisterTable();
        jLabel1.setText(this.manager.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registerNew = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCompanyName = new javax.swing.JTextField();
        txtAsset = new javax.swing.JTextField();
        txtLiab = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        requestListing = new javax.swing.JPanel();
        txtNumberOfShares = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtPricePerShare = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        InvestmentManager = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboCompanyName = new javax.swing.JComboBox<>();
        lblAssets = new javax.swing.JLabel();
        lblLiibli = new javax.swing.JLabel();
        lblMarkcap = new javax.swing.JLabel();
        lblExperince = new javax.swing.JLabel();
        lblsalary = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblApplications = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        listingStatusJpanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblListingStatus = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        homepage = new javax.swing.JPanel();
        btnNewIM = new javax.swing.JButton();
        btnRegisterNewCom = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableRegisterComp = new javax.swing.JTable();
        btnRequestListing = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1000, 1000));
        setLayout(new java.awt.CardLayout());

        registerNew.setBackground(new java.awt.Color(255, 255, 255));
        registerNew.setMaximumSize(new java.awt.Dimension(1000, 1000));
        registerNew.setPreferredSize(new java.awt.Dimension(1000, 1000));
        registerNew.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Enter the below details to register your company");
        registerNew.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 139, 664, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Company Name:");
        registerNew.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 148, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Assets (USD):");
        registerNew.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Liabilities (USD):");
        registerNew.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 148, -1));

        txtCompanyName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtCompanyName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCompanyNameActionPerformed(evt);
            }
        });
        registerNew.add(txtCompanyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 200, -1));

        txtAsset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtAsset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAssetActionPerformed(evt);
            }
        });
        registerNew.add(txtAsset, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 200, -1));

        txtLiab.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtLiab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLiabActionPerformed(evt);
            }
        });
        registerNew.add(txtLiab, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 200, -1));

        jButton2.setBackground(new java.awt.Color(85, 65, 118));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Register ");
        jButton2.setAutoscrolls(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        registerNew.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 150, 40));

        jPanel5.setBackground(new java.awt.Color(85, 65, 118));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(1100, 80));

        jLabel2.setBackground(new java.awt.Color(85, 65, 118));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("New Company Registration ");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("<< Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jButton1)
                .addGap(106, 106, 106)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(532, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        registerNew.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, -1));

        add(registerNew, "card3");

        requestListing.setBackground(new java.awt.Color(255, 255, 255));

        txtNumberOfShares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumberOfSharesActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Enter Number of Shares:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Price Per Share:");

        jButton3.setBackground(new java.awt.Color(85, 65, 118));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Request");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(85, 65, 118));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.setToolTipText("");
        jPanel4.setPreferredSize(new java.awt.Dimension(1000, 80));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jButton5.setText("<< Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jButton5)
                .addContainerGap(972, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jButton5)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout requestListingLayout = new javax.swing.GroupLayout(requestListing);
        requestListing.setLayout(requestListingLayout);
        requestListingLayout.setHorizontalGroup(
            requestListingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(requestListingLayout.createSequentialGroup()
                .addGroup(requestListingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(requestListingLayout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addGroup(requestListingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(requestListingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumberOfShares, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPricePerShare, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(requestListingLayout.createSequentialGroup()
                        .addGap(304, 304, 304)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1094, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(347, Short.MAX_VALUE))
        );
        requestListingLayout.setVerticalGroup(
            requestListingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(requestListingLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addGroup(requestListingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumberOfShares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(requestListingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtPricePerShare, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(472, Short.MAX_VALUE))
        );

        add(requestListing, "card4");

        InvestmentManager.setBackground(new java.awt.Color(255, 255, 255));
        InvestmentManager.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Select Company");
        InvestmentManager.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 171, 118, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("Select Manager");
        InvestmentManager.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 210, -1));

        jComboCompanyName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboCompanyName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboCompanyNameActionPerformed(evt);
            }
        });
        InvestmentManager.add(jComboCompanyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 168, -1, -1));
        InvestmentManager.add(lblAssets, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 549, 50, 14));
        InvestmentManager.add(lblLiibli, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 575, 50, 19));
        InvestmentManager.add(lblMarkcap, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 603, 50, 14));
        InvestmentManager.add(lblExperince, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 549, 50, 14));
        InvestmentManager.add(lblsalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 575, 50, 19));

        jButton4.setBackground(new java.awt.Color(85, 65, 118));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Assign Investment Mangaer");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        InvestmentManager.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 250, 50));

        tblApplications.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Experience", "Salary Expected"
            }
        ));
        jScrollPane3.setViewportView(tblApplications);

        InvestmentManager.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 248, 672, 146));

        jPanel3.setBackground(new java.awt.Color(85, 65, 118));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(1000, 80));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Assigning Investment Manager");

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("<< Back");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 977, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButton6)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        InvestmentManager.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 70));

        add(InvestmentManager, "card5");

        listingStatusJpanel.setBackground(new java.awt.Color(255, 255, 255));

        tblListingStatus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Company", "Stock Quantity", "Stock Price", "Listing Status"
            }
        ));
        jScrollPane2.setViewportView(tblListingStatus);

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 30)); // NOI18N
        jLabel7.setText("My Companies Listing Status:");

        jPanel2.setBackground(new java.awt.Color(85, 65, 118));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setToolTipText("");

        jLabel8.setBackground(new java.awt.Color(85, 65, 118));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Welcome Company Manager ");

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jButton9.setText("<< Back");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 1281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 49, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButton9)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout listingStatusJpanelLayout = new javax.swing.GroupLayout(listingStatusJpanel);
        listingStatusJpanel.setLayout(listingStatusJpanelLayout);
        listingStatusJpanelLayout.setHorizontalGroup(
            listingStatusJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listingStatusJpanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(listingStatusJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(listingStatusJpanelLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        listingStatusJpanelLayout.setVerticalGroup(
            listingStatusJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listingStatusJpanelLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(426, Short.MAX_VALUE))
        );

        add(listingStatusJpanel, "card6");

        homepage.setBackground(new java.awt.Color(255, 255, 255));
        homepage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNewIM.setBackground(new java.awt.Color(85, 65, 118));
        btnNewIM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNewIM.setForeground(new java.awt.Color(255, 255, 255));
        btnNewIM.setText("Assigning Investment Manager");
        btnNewIM.setActionCommand("");
        btnNewIM.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(204, 204, 204)));
        btnNewIM.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNewIM.setPreferredSize(new java.awt.Dimension(177, 25));
        btnNewIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewIMActionPerformed(evt);
            }
        });
        homepage.add(btnNewIM, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 240, 30));

        btnRegisterNewCom.setBackground(new java.awt.Color(85, 65, 118));
        btnRegisterNewCom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegisterNewCom.setForeground(new java.awt.Color(255, 255, 255));
        btnRegisterNewCom.setText("Register New Company");
        btnRegisterNewCom.setActionCommand("");
        btnRegisterNewCom.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(204, 204, 204)));
        btnRegisterNewCom.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRegisterNewCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterNewComActionPerformed(evt);
            }
        });
        homepage.add(btnRegisterNewCom, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 200, 30));

        tableRegisterComp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Company Name", "Assets", "Liabilities", "Market Cap", "Liscence Request", "Listing Request", "Investment Manager"
            }
        ));
        jScrollPane1.setViewportView(tableRegisterComp);

        homepage.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 692, 138));

        btnRequestListing.setBackground(new java.awt.Color(85, 65, 118));
        btnRequestListing.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRequestListing.setForeground(new java.awt.Color(255, 255, 255));
        btnRequestListing.setText("Request Listing");
        btnRequestListing.setToolTipText("");
        btnRequestListing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestListingActionPerformed(evt);
            }
        });
        homepage.add(btnRequestListing, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, -1, 40));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel21.setText("My Companies");
        homepage.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 190, 40));

        jPanel1.setBackground(new java.awt.Color(85, 65, 118));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");
        jPanel1.setPreferredSize(new java.awt.Dimension(1300, 80));
        jPanel1.setVerifyInputWhenFocusTarget(false);

        jLabel1.setBackground(new java.awt.Color(85, 65, 118));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome Company Manager ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1030, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        homepage.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 70));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/stockops/UI/CompanyManger/commannnn.jpg"))); // NOI18N
        jLabel13.setText("jLabel13");
        jLabel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(85, 65, 118), 3, true));
        jLabel13.setPreferredSize(new java.awt.Dimension(400, 400));
        homepage.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 670, 370));

        add(homepage, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterNewComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterNewComActionPerformed
        setComponent(registerNew);
        populateRegisterTable();
    }//GEN-LAST:event_btnRegisterNewComActionPerformed

    private void txtCompanyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCompanyNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCompanyNameActionPerformed

    private void txtAssetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAssetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAssetActionPerformed

    private void txtLiabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLiabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLiabActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            Company company = new Company();
            if(this.business.getEstablishment().getEstablishmentsModerator().getCompanyByName(txtCompanyName.getText())!=null){
                JOptionPane.showMessageDialog(this, "Company With the Given Name Already Exists!");
            }
            else{
                company.setName(txtCompanyName.getText());
                Double assets = Double.parseDouble(txtAsset.getText());
                Double liab = Double.parseDouble(txtLiab.getText());
                company.setLiabilities(liab);
                company.setAssets(assets);
                company.setLiscenceStatus("Pending");
                company.setListingRequestStatus("Not Initiated");
                company.setCaptial(assets-liab);
                company.setBalance(assets-liab);
                company.setCompanyManager(manager);
                this.manager.getCompanyList().add(company);
                this.business.getEstablishment().getEstablishmentsModerator().getCompanyList().add(company);
                populateRegisterTable();
                JOptionPane.showMessageDialog(this, "Company "+company.getName() +" successfully registered! \n"+"    Market Cap:"+String.valueOf(assets-liab));
                setComponent(homepage);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Assets and Liabilities Should Be Numbers!");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnRequestListingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestListingActionPerformed
        String selectedCompanyName=String.valueOf(tableRegisterComp.getValueAt(tableRegisterComp.getSelectedRow(), 0));
        Company selectedCompanyForListing = this.business.getEstablishment().getEstablishmentsModerator().getCompanyByName(selectedCompanyName);
        if(selectedCompanyForListing.getLiscenceStatus().equals("Approved")){
            if(selectedCompanyForListing.getListingRequestStatus().equals("Approved")){
                JOptionPane.showMessageDialog(this, "This company is already listed");
            }
            else{
                this.selectedCompany = selectedCompanyForListing;
                setComponent(requestListing);
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "This company does not have a lisence to run a business");
        }

    }//GEN-LAST:event_btnRequestListingActionPerformed

    private void txtNumberOfSharesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumberOfSharesActionPerformed

        int numberOfShares = Integer.parseInt(txtNumberOfShares.getText());
        txtPricePerShare.setText(String.valueOf(selectedCompany.getCaptial()/numberOfShares));
        
    }//GEN-LAST:event_txtNumberOfSharesActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
            int numberOfShares = Integer.parseInt(txtNumberOfShares.getText());
            Double pricePerShare = selectedCompany.getCaptial()/numberOfShares;
            ListingRequest listingRequest = new ListingRequest(this.selectedCompany, pricePerShare, numberOfShares);
            this.selectedCompany.setListingRequestStatus("Pending");
            for(ListingRequest listReq: this.business.getMarket().getEquityMarket().getEquityMarketModerator().getListingRequestList()){
                if(listReq.getCompany().getName().equals(selectedCompany.getName())){
                    this.business.getMarket().getEquityMarket().getEquityMarketModerator().getListingRequestList().remove(listReq);
                }
            }
            this.business.getMarket().getEquityMarket().getEquityMarketModerator().getListingRequestList().add(listingRequest);
            int requestCount =this.business.getMarket().getEquityMarket().getEquityMarketModerator().getRequestCount();
            listingRequest.setRequestId(requestCount);
            this.business.getMarket().getEquityMarket().getEquityMarketModerator().setRequestCount(requestCount+1);
            txtPricePerShare.setText(String.valueOf(pricePerShare));
            JOptionPane.showMessageDialog(this, "Request Sent!");
            populateListingTable();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Number of shares should be an integer!");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnNewIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewIMActionPerformed
        jComboCompanyName.removeAllItems();
        for(Company company: this.manager.getCompanyList()){
            jComboCompanyName.addItem(company.getName());
        }
        setComponent(InvestmentManager);      
    }//GEN-LAST:event_btnNewIMActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setComponent(homepage);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        setComponent(homepage);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        setComponent(homepage);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        setComponent(homepage);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jComboCompanyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboCompanyNameActionPerformed
        populateJobRequestTable();
    }//GEN-LAST:event_jComboCompanyNameActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try{
            Company selectedCompany = this.business.getEstablishment().getEstablishmentsModerator().getCompanyByName(String.valueOf(jComboCompanyName.getSelectedItem()));
            InvestmentManager applicant = this.business.getEstablishment().getEstablishmentsModerator().getInvestmentManagerByName(String.valueOf(tblApplications.getValueAt(tblApplications.getSelectedRow(), 0)));
            if(selectedCompany.getInvestmentManager()!=null){
                selectedCompany.getInvestmentManager().setAssignedCompany(null);
            }
            selectedCompany.setInvestmentManager(applicant);
            applicant.setAssignedCompany(selectedCompany);
            JOptionPane.showMessageDialog(this, "Investment Manager Successfully Assigned");
            selectedCompany.getJobRequest().remove(selectedCompany.getJobRequest().get(tblApplications.getSelectedRow()));
            populateJobRequestTable();
            populateListingTable();
            populateListingRequestTable();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Something went wrong");
        }
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel InvestmentManager;
    private javax.swing.JButton btnNewIM;
    private javax.swing.JButton btnRegisterNewCom;
    private javax.swing.JButton btnRequestListing;
    private javax.swing.JPanel homepage;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboCompanyName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAssets;
    private javax.swing.JLabel lblExperince;
    private javax.swing.JLabel lblLiibli;
    private javax.swing.JLabel lblMarkcap;
    private javax.swing.JLabel lblsalary;
    private javax.swing.JPanel listingStatusJpanel;
    private javax.swing.JPanel registerNew;
    private javax.swing.JPanel requestListing;
    private javax.swing.JTable tableRegisterComp;
    private javax.swing.JTable tblApplications;
    private javax.swing.JTable tblListingStatus;
    private javax.swing.JTextField txtAsset;
    private javax.swing.JTextField txtCompanyName;
    private javax.swing.JTextField txtLiab;
    private javax.swing.JTextField txtNumberOfShares;
    private javax.swing.JLabel txtPricePerShare;
    // End of variables declaration//GEN-END:variables

    private void setComponent(JPanel jPanel) {
        this.removeAll();
        this.add(jPanel);
        this.revalidate();
        this.repaint();
    }

    private void populateRegisterTable() {
        DefaultTableModel model = (DefaultTableModel) tableRegisterComp.getModel();
        model.setRowCount(0);
        for(Company company: this.manager.getCompanyList()){
            Object[] row= new Object[7];
            row[0]=company.getName();
            row[1]=company.getAssets();
            row[2]=company.getLiabilities();
            row[3]=company.getCaptial();
            row[4]=company.getLiscenceStatus();
            row[5]=company.getListingRequestStatus();
            if(company.getInvestmentManager()==null){
                row[6]="Not Assigned";
            }
            else{
                row[6]=company.getInvestmentManager().getName();
            }
            model.addRow(row);
        }
    }

    private void populateListingTable() {
        DefaultTableModel model = (DefaultTableModel) tableRegisterComp.getModel();
        model.setRowCount(0);
        for(Company company: this.manager.getCompanyList()){
            Object[] row= new Object[7];
            row[0]=company.getName();
            row[1]=company.getAssets();
            row[2]=company.getLiabilities();
            row[3]=company.getCaptial();
            row[4]=company.getLiscenceStatus();
            row[5]=company.getListingRequestStatus();
            if(company.getInvestmentManager()==null){
                row[6]="Not Assigned";
            }
            else{
                row[6]=company.getInvestmentManager().getName();
            }
            model.addRow(row);
        }
    }

    private void populateListingRequestTable() {
        DefaultTableModel model = (DefaultTableModel)tblListingStatus.getModel();
        model.setRowCount(0);
        for(Company company: this.manager.getCompanyList()){
            Object[] row=new Object[4];
            row[0]=company.getName();
            row[3]=company.getListingRequestStatus();
            if(!company.getListingRequestStatus().equals("Listed")){
                row[1]="NA";
                row[2]="NA";
            }
            else{
                for(Equity equity: this.business.getMarket().getEquityMarket().getEquityList()){
                    if(equity.getCompany()==company){
                        row[1]=equity.getSymbol();
                        row[2]=equity.getPrice();
                    }
                }
            }
            model.addRow(row);
        }
        
    }

    private void populateJobRequestTable() {
        Company selectedCompany = this.business.getEstablishment().getEstablishmentsModerator().getCompanyByName(String.valueOf(jComboCompanyName.getSelectedItem()));
        if(selectedCompany==null){
            selectedCompany=this.manager.getCompanyList().get(0);
        }
        DefaultTableModel model = (DefaultTableModel) tblApplications.getModel();
        model.setRowCount(0);
        for(JobRequest jobRequest: selectedCompany.getJobRequest()){
            if(jobRequest.getApplicant().getAssignedCompany()==null){
                Object[] row= new Object[3];
                row[0]=jobRequest.getApplicant().getName();
                row[1]=jobRequest.getExperience();
                row[2]=jobRequest.getSalaryRequest();
                model.addRow(row);
            }
        }
    }
}
